Add support for `$update`'s `$set` operator dot notation
FerretDB/FerretDB pull request #1008
Opened 2022-08-08 18:05 UTC by w84thesun

# Description

This PR closes #803.

## Readiness checklist

* [ ] I added tests for new functionality or bugfixes.
* [ ] I ran `task all`, and it passed.
* [ ] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [ ] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)),
      Assignee, Labels, Project and project's Sprint fields.
* [ ] I marked all done items in this checklist.

2022-08-09 15:45 UTC, noisersup requested changes

2022-08-09 15:45 UTC, noisersup commented on internal/handlers/common/update.go
> +func processSetFieldExpression(doc, setDoc *types.Document, setOnInsert bool) (bool, error) {
```suggestion
// processSetFieldExpression changes document according to $set and $setOnInsert operators.
// If the document was changed it returns true.
func processSetFieldExpression(doc, setDoc *types.Document, setOnInsert bool) (bool, error) {
```

2022-08-10 07:03 UTC, rumyantseva approved these changes
I'm not sure if we have enough test cases, but I can't come up with new ones. The logic looks correct to me as well. So, LGTM overall :)

2022-08-10 09:33 UTC, noisersup approved these changes

2022-08-10 11:22 UTC, AlekSi approved these changes

2022-08-10 11:23 UTC, merged