Less strict delta for `dataSize` in tests
FerretDB/FerretDB pull request #1053
Opened 2022-08-18 07:11 UTC by rumyantseva

# Description

As Tigris provides data size estimation, this number is not very accurate and may vary.
I set  35500 as the biggest number I've seen in tests.

## Readiness checklist

* [ ] I added tests for new functionality or bugfixes.
* [ ] I ran `task all`, and it passed.
* [ ] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [ ] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [ ] I marked all done items in this checklist.

2022-08-18 08:04 UTC, w84thesun submitted a review, later dismissed

2022-08-18 09:44 UTC, AlekSi approved these changes

2022-08-18 12:12 UTC, noisersup requested changes
There are some test issues:
```
        	Error:      	Max difference between 8192 and 35500 allowed is 8192, but difference was -27308

```

2022-08-19 16:09 UTC, noisersup approved these changes
LGTM

2022-08-22 15:12 UTC, AlekSi approved these changes

2022-08-22 15:12 UTC, merged