Update introduction documentation
FerretDB/FerretDB pull request #1174
Opened 2022-09-22 08:20 UTC by Fashander

# Description

This PR closes #1163 .

## Readiness checklist

* [ ] I added tests for new functionality or bugfixes.
* [ ] I ran `task all`, and it passed.
* [ ] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [x] I ensured that the title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

2022-09-22 08:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FerretDB/FerretDB?pullRequest=1174) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/FerretDB/FerretDB?pullRequest=1174) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Fashander<br/>:x: fashander<br/><hr/>**fashander** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FerretDB/FerretDB?pullRequest=1174) it.</sub>

2022-09-22 10:59 UTC, AlekSi requested changes

2022-09-22 10:59 UTC, AlekSi commented on website/docs/intro.md
> +* name cannot start with the reserved prefix _ferretdb_.
The prefix is really `_ferretdb_`, not just `ferretdb`. Without backticks it will italic in Markdown

2022-09-22 11:19 UTC, noisersup commented on website/docs/intro.md
> -and [contributing guidelines](https://github.com/FerretDB/FerretDB/blob/main/CONTRIBUTING.md/).
Shouldn't we leave this somewhere?

2022-09-23 08:04 UTC, AlekSi approved these changes

2022-09-23 08:16 UTC, merged