Migrate FerretDB and envtool to Kong
FerretDB/FerretDB pull request #1184
Opened 2022-09-27 10:06 UTC by noisersup

# Description

This PR closes #1156.

## Readiness checklist

* [ ] I added tests for new functionality or bugfixes.
* [ ] I ran `task all`, and it passed.
* [ ] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [ ] I ensured that the title is good enough for the changelog.
* [ ] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [ ] I marked all done items in this checklist.

2022-09-28 00:53 UTC, noisersup commented
```
> go run ./cmd/ferretdb --help
Usage: ferretdb

Flags:
  -h, --help                                                            Show context-sensitive help.
      --version                                                         Print version to stdout (full version, commit, branch, dirty flag) and exit.
      --listen-addr="127.0.0.1:27017"                                   Listen address.
      --proxy-addr="127.0.0.1:37017"                                    Proxy address.
      --debug-addr="127.0.0.1:8088"                                     Debug address.
      --mode="normal"                                                   Operation mode: [normal proxy diff-normal diff-proxy].
      --test-record=""                                                  Directory of record files with binary data coming from connected clients.
      --handler="pg"                                                    Backend handler: dummy, pg.
      --postgresql-url="postgres://postgres@127.0.0.1:5432/ferretdb"    PostgreSQL URL.
      --log-level="debug"                                               Log level: debug, info, warn, error.
      --test-conn-timeout=0                                             Test: set connection timeout.
```
```
> go run -tags=ferretdb_tigris ./cmd/ferretdb --help
Usage: ferretdb

Flags:
  -h, --help                                                            Show context-sensitive help.
      --version                                                         Print version to stdout (full version, commit, branch, dirty flag) and exit.
      --listen-addr="127.0.0.1:27017"                                   Listen address.
      --proxy-addr="127.0.0.1:37017"                                    Proxy address.
      --debug-addr="127.0.0.1:8088"                                     Debug address.
      --mode="normal"                                                   Operation mode: [normal proxy diff-normal diff-proxy].
      --test-record=""                                                  Directory of record files with binary data coming from connected clients.
      --handler="pg"                                                    Backend handler: dummy, pg, tigris.
      --postgresql-url="postgres://postgres@127.0.0.1:5432/ferretdb"    PostgreSQL URL.
      --log-level="debug"                                               Log level: debug, info, warn, error.
      --test-conn-timeout=0                                             Test: set connection timeout.
      --tigris-client-id=""                                             Tigris Client ID.
      --tigris-client-secret=""                                         Tigris Client secret.
      --tigris-token=""                                                 Tigris token.
      --tigris-url="http://127.0.0.1:8081/"                             Tigris URL.
```
```
> go run ./cmd/envtool --help
Usage: envtool

Flags:
  -h, --help     Show context-sensitive help.
      --debug    Enable debug mode.
```

2022-09-28 13:38 UTC, AlekSi commented
@noisersup Please merge with `main`

2022-09-28 14:07 UTC, AlekSi reviewed
Let's try something like that:

```go
var cli struct {
  // ...
}

func main() {
  initCLI()
  run()
}

func initCLI() {
  kong.Parse(&cli, ...)
  // ...
}

func run() {
  // main logic that uses populated `cli`
}

func TestMain(m *testing.M) {
 // magic
}
```

I'm not sure what the magic is yet, but not calling `kong.Parse` or any other kong code inside `run()` should be the first step

2022-09-29 15:37 UTC, noisersup commented on cmd/ferretdb/main_test.go
> +	i := slices.Index(os.Args, "--")
Complex problems require simple solutions :) I

2022-09-30 10:12 UTC, w84thesun submitted a review, later dismissed
LGTM

2022-09-30 10:42 UTC, AlekSi requested changes
> I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).

That is not done

2022-09-30 10:45 UTC, AlekSi commented on cmd/ferretdb/main.go
> +		if cli.Mode == string(m) {
I think we could refactor it by using `slices.Contains`

2022-09-30 10:53 UTC, noisersup commented
> That is not done

Should we comment `run()`?

2022-09-30 11:43 UTC, AlekSi commented
> Should we comment run()?

> "unexported top-level declarations (functions, [...])"

Yes, we should :)

2022-09-30 12:22 UTC, AlekSi approved these changes

2022-09-30 12:25 UTC, w84thesun approved these changes

2022-09-30 12:25 UTC, merged