Documentation for contributors
FerretDB/FerretDB pull request #1194
Opened 2022-09-29 12:35 UTC by Fashander

# Description

This PR closes #1164 .

## Readiness checklist

* [ ] I added tests for new functionality or bugfixes.
* [ ] I ran `task all`, and it passed.
* [ ] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [x] I ensured that the title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

2022-09-29 12:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FerretDB/FerretDB?pullRequest=1194) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/FerretDB/FerretDB?pullRequest=1194) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Fashander<br/>:x: fashander<br/><hr/>**fashander** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FerretDB/FerretDB?pullRequest=1194) it.</sub>

2022-09-29 14:04 UTC, AlekSi commented on website/docs/contributing.md
> +* [dance (stub)](https://github.com/FerretDB/dance): This repository is a FerretDB integration testing tool.
Dance is not a stub :) Not sure why I wrote that.

Also, I think we should move it above github-actions

2022-09-29 14:04 UTC, AlekSi commented on website/docs/contributing.md
> +Read the [CONTRIBUTING.md](https://github.com/FerretDB/FerretDB/blob/main/CONTRIBUTING.md) and [CODE_OF_CONDUCT.md](https://github.com/FerretDB/FerretDB/blob/main/CODE_OF_CONDUCT.md) files to know mo
The idea was to link to https://github.com/FerretDB/FerretDB/blob/main/CONTRIBUTING.md for FerretDB, to https://github.com/FerretDB/dance/blob/main/CONTRIBUTING.md for dance, and to a separate CONTRIBUTING.md in github-actions repo afte FerretDB/github-actions#96

2022-09-29 16:30 UTC, noisersup approved these changes

2022-10-03 06:18 UTC, AlekSi commented on website/docs/contributing.md
> +* For first-time contributors looking for issues to work on, kindly check the issues that are labeled [good-first-issues](https://github.com/FerretDB/FerretDB/issues?q=is%3Aissue+is%3Aopen+label%3A%2
I think we should link to https://github.com/FerretDB/FerretDB/contribute instead

2022-10-03 06:18 UTC, AlekSi commented on website/docs/contributing.md
> +If you have any questions or suggestions on how we can improve, kindly join our [Slack chat](https://github.com/FerretDB/FerretDB/discussions) or [GitHub discussions](https://join.slack.com/t/ferretd
Could we link to `/intro/#community` instead? I'm a bit worried about that Slack URL that should be updated from time to time being in too many places

2022-10-03 16:18 UTC, AlekSi commented on website/docs/contributing.md
> +## Contributing to github-actions
Let's link to https://github.com/FerretDB/github-actions/blob/main/CONTRIBUTING.md)

2022-10-05 09:23 UTC, w84thesun approved these changes
LGTM

2022-10-05 09:24 UTC, rumyantseva reviewed
LGTM overall, a couple of suggestions (feel free to reject).

2022-10-05 09:24 UTC, rumyantseva commented on website/docs/contributing.md
> +* [dance (stub)](https://github.com/FerretDB/dance): This repository is a FerretDB integration testing tool.
```suggestion
* [dance](https://github.com/FerretDB/dance): This repository is a FerretDB integration testing tool.
```

2022-10-05 09:24 UTC, rumyantseva commented on website/docs/contributing.md
> +* For first-time contributors looking for issues to work on, kindly check the issues that are labeled [good-first-issues](https://github.com/FerretDB/FerretDB/contribute)
Maybe something like 

```suggestion
* The most straightforward way to start contributing is to take issues that are labeled [good-first-issues](https://github.com/FerretDB/FerretDB/contribute) 😉
```

I believe, not only first time contributors might want to start from those.

2022-10-05 09:33 UTC, AlekSi requested changes

2022-10-05 09:33 UTC, AlekSi commented on website/docs/contributing.md
> +* [dance (stub)](https://github.com/FerretDB/dance): This repository is a FerretDB integration testing tool.
That wasn't done

2022-10-05 14:19 UTC, rumyantseva approved these changes
LGTM

2022-10-05 16:15 UTC, AlekSi approved these changes

2022-10-05 16:15 UTC, merged