Hacks hacks hacks
FerretDB/FerretDB pull request #1261
Opened 2022-10-14 10:19 UTC by AlekSi

Don't mind me, I'm just building Docker images there.

2022-11-07 06:16 UTC, chilagrow approved these changes

2022-11-07 09:59 UTC, noisersup requested changes
It seems that `TestCommandsReplicationIsMaster` tests are failing because of different wire versions

2022-11-07 13:37 UTC, noisersup approved these changes

2022-11-08 01:40 UTC, chilagrow approved these changes

2022-11-08 08:52 UTC, merged