Fix `explain` command
FerretDB/FerretDB pull request #1294
Opened 2022-10-20 11:29 UTC by w84thesun

# Description

Closes #1257.

## Readiness checklist

* [x] I added tests for new functionality or bugfixes.
* [ ] I ran `task all`, and it passed.
* [ ] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [x] I ensured that the title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

2022-10-20 14:40 UTC, rumyantseva requested changes
Hmmm, I tried to run it locally on your branch, but got a panic.

I have `test` database filled by `task env-data`.

This is the command:
```
test> db.doubles.find().explain()
MongoNetworkError: connection 5 to 127.0.0.1:27017 closed
```

This is the panic trace:
```
2022-10-20T16:37:58.101+0200	DEBUG	common/unimplemented.go:57	ignoring field	{"command": "explain", "field": "verbosity"}
2022-10-20T16:37:58.104+0200	INFO	pgdb	v4@v4.17.2/conn.go:354	Exec	{"sql": "begin", "args": [], "time": "2.856417ms", "commandTag": "BEGIN", "pid": 732}
2022-10-20T16:37:58.107+0200	INFO	pgdb	v4@v4.17.2/conn.go:354	Query	{"sql": "SELECT nspname FROM pg_catalog.pg_namespace WHERE nspname = $1", "args": ["test"], "time": "2.539416ms", "rowCount": 1, "pid": 732}
2022-10-20T16:37:58.111+0200	INFO	pgdb	v4@v4.17.2/conn.go:354	Query	{"pid": 732, "sql": "SELECT settings FROM \"test\".\"_ferretdb_settings\"", "args": [], "time": "4.463ms", "rowCount": 1}
2022-10-20T16:37:58.113+0200	INFO	pgdb	v4@v4.17.2/conn.go:354	Query	{"time": "1.55975ms", "rowCount": 1, "pid": 732, "sql": "SELECT nspname FROM pg_catalog.pg_namespace WHERE nspname = $1", "args": ["test"]}
2022-10-20T16:37:58.118+0200	INFO	pgdb	v4@v4.17.2/conn.go:354	Query	{"sql": "SELECT table_name FROM information_schema.columns WHERE table_schema = $1 GROUP BY table_name ORDER BY table_name", "args": ["test"], "time": "5.290917ms", "rowCount": 19, "pid": 732}
2022-10-20T16:37:58.120+0200	INFO	pgdb	v4@v4.17.2/conn.go:354	Query	{"time": "1.697708ms", "rowCount": 1, "pid": 732, "sql": "SELECT settings FROM \"test\".\"_ferretdb_settings\"", "args": []}
2022-10-20T16:37:58.122+0200	INFO	pgdb	v4@v4.17.2/conn.go:354	Query	{"rowCount": 1, "pid": 732, "sql": "EXPLAIN (VERBOSE true, FORMAT JSON)  SELECT _jsonb  FROM \"test\".\"doubles_cd095ea1\"", "args": [], "time": "2.423291ms"}
2022-10-20T16:37:58.124+0200	INFO	pgdb	v4@v4.17.2/conn.go:354	Exec	{"args": [], "time": "1.102417ms", "commandTag": "COMMIT", "pid": 732, "sql": "commit"}
2022-10-20T16:37:58.124+0200	DEBUG	// 127.0.0.1:58166 -> 127.0.0.1:27017 	clientconn/conn.go:465	Response header: length:   558, id:    4, response_to:   35, opcode: OP_MSG
2022-10-20T16:37:58.124+0200	DEBUG	// 127.0.0.1:58166 -> 127.0.0.1:27017 	clientconn/conn.go:466	Response message:
{
  "Checksum": 0,
  "FlagBits": 0,
  "Sections": [
    {
      "Document": {
        "$k": [
          "queryPlanner",
          "explainVersion",
          "command",
          "serverInfo",
          "ok"
        ],
        "queryPlanner": {
          "$k": [
            "Plan"
          ],
          "Plan": {
            "$k": [
              "Async Capable",
              "Relation Name",
              "Total Cost",
              "Plan Width",
              "Node Type",
              "Parallel Aware",
              "Schema",
              "Alias",
              "Startup Cost",
              "Plan Rows",
              "Output"
            ],
            "Async Capable": false,
            "Relation Name": "doubles_cd095ea1",
            "Total Cost": {
              "$f": 23.6
            },
            "Plan Width": {
              "$f": 32
            },
            "Node Type": "Seq Scan",
            "Parallel Aware": false,
            "Schema": "test",
            "Alias": "doubles_cd095ea1",
            "Startup Cost": {
              "$f": 0
            },
            "Plan Rows": {
              "$f": 1360
            },
            "Output": [
              "_jsonb"
            ]
          }
        },
        "explainVersion": "1",
        "command": {
          "$k": [
            "find",
            "filter",
            "$db"
          ],
          "find": "doubles",
          "filter": {
            "$k": []
          },
          "$db": "test"
        },
        "serverInfo": {
          "$k": [
            "host",
            "port",
            "version",
            "gitVersion",
            "ferretdbVersion"
          ],
          "host": "ferretdb",
          "port": 58166,
          "version": "6.0.42",
          "gitVersion": "c5cb3de03fa8c9daafb4bdf01b905c895645afdb",
          "ferretdbVersion": "v0.5.4-82-gc5cb3de"
        },
        "ok": {
          "$f": 1
        }
      },
      "Kind": 0
    }
  ]
}

2022-10-20T16:37:58.124+0200	DPANIC	// 127.0.0.1:58166 -> 127.0.0.1:27017 	clientconn/conn.go:145	expected length 116 (marshaled body size) + 16 (fixed marshaled header size) = 132, got 118
(err = <nil>)
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run.func2
	github.com/FerretDB/FerretDB/internal/clientconn/conn.go:145
runtime.gopanic
	runtime/panic.go:890
github.com/FerretDB/FerretDB/internal/wire.WriteMessage
	github.com/FerretDB/FerretDB/internal/wire/msg_body.go:106
github.com/FerretDB/FerretDB/internal/handlers/proxy.(*Router).Route
	github.com/FerretDB/FerretDB/internal/handlers/proxy/proxy.go:57
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run
	github.com/FerretDB/FerretDB/internal/clientconn/conn.go:226
github.com/FerretDB/FerretDB/internal/clientconn.acceptLoop.func1
	github.com/FerretDB/FerretDB/internal/clientconn/listener.go:198
panic: expected length 116 (marshaled body size) + 16 (fixed marshaled header size) = 132, got 118 [recovered]
	panic: expected length 116 (marshaled body size) + 16 (fixed marshaled header size) = 132, got 118
(err = <nil>)

goroutine 109 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2, 0xc00025f520, {0x105c6d9a1?, 0x42?, 0xc0004ca580?})
	go.uber.org/zap@v1.23.0/zapcore/entry.go:198 +0xb0
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00025f520, {0x0, 0x0, 0x0})
	go.uber.org/zap@v1.23.0/zapcore/entry.go:264 +0x3b4
go.uber.org/zap.(*SugaredLogger).log(0xc000128050, 0x3, {0x105797483, 0xd}, {0xc0004bb268, 0x2, 0x2}, {0x0, 0x0, 0x0})
	go.uber.org/zap@v1.23.0/sugar.go:287 +0x10c
go.uber.org/zap.(*SugaredLogger).DPanicf(...)
	go.uber.org/zap@v1.23.0/sugar.go:176
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run.func2()
	github.com/FerretDB/FerretDB/internal/clientconn/conn.go:145 +0x134
panic({0x105a14600, 0xc00042f2e0})
	runtime/panic.go:890 +0x258
github.com/FerretDB/FerretDB/internal/wire.WriteMessage(0xc000128040?, 0xc000411a60, {0x105baffc0, 0xc0000902e0})
	github.com/FerretDB/FerretDB/internal/wire/msg_body.go:106 +0x28c
github.com/FerretDB/FerretDB/internal/handlers/proxy.(*Router).Route(0xc000132020, {0x105baf3d8, 0xc000649470}, 0xc00020b7a0?, {0x105baffc0, 0xc0000902e0})
	github.com/FerretDB/FerretDB/internal/handlers/proxy/proxy.go:57 +0xc4
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run(0xc000524a80, {0x105baf3d8?, 0xc000649470})
	github.com/FerretDB/FerretDB/internal/clientconn/conn.go:226 +0xcfc
github.com/FerretDB/FerretDB/internal/clientconn.acceptLoop.func1()
	github.com/FerretDB/FerretDB/internal/clientconn/listener.go:198 +0x8b8
created by github.com/FerretDB/FerretDB/internal/clientconn.acceptLoop
	github.com/FerretDB/FerretDB/internal/clientconn/listener.go:164 +0x300
task: Failed to run task "run": exit status 2
```

2022-10-20 14:44 UTC, rumyantseva commented
Something like
```
test> db.doubles.find({"_id": "double"}).explain()
```

causes panic too. 

Full logs:

```
elena@ferretdb ~/w/FerretDB (issue-1257-fix-explain-command) [1]> task run
task: [gen-version] go generate -x ./internal/util/version
go run ./generate.go
task: [build-testcover] go test -c -o=bin/ferretdb-testcover -trimpath -race=true -tags=ferretdb_testcover,ferretdb_tigris -coverpkg=./... ./cmd/ferretdb
task: [run] bin/ferretdb-testcover -test.coverprofile=cover.txt -- --test-records-dir=records --mode=diff-normal --listen-addr=:27017
2022-10-20T16:42:48.045+0200	INFO	ferretdb/main.go:183	Starting FerretDB v0.5.4-82-gc5cb3de...	{"version": "v0.5.4-82-gc5cb3de", "commit": "c5cb3de03fa8c9daafb4bdf01b905c895645afdb", "branch": "issue-1257-fix-explain-command", "dirty": false, "debug": true, "buildEnvironment": {"CGO_ENABLED":"1","GOARCH":"arm64","GOOS":"darwin","buildtags":"ferretdb_testcover,ferretdb_tigris","compiler":"gc","race":"true","trimpath":"true"}, "uuid": "9c84a742-e8e6-46fc-a2b0-11cefc534be9"}
2022-10-20T16:42:48.046+0200	INFO	debug	debug/debug.go:60	Starting debug server on http://127.0.0.1:8088/
2022-10-20T16:42:48.046+0200	INFO	listener	clientconn/listener.go:80	Listening on [::]:27017 ...
2022-10-20T16:42:48.046+0200	INFO	listener	clientconn/listener.go:135	Waiting for all connections to stop...





2022-10-20T16:42:56.379+0200	INFO	listener	clientconn/listener.go:196	Connection started	{"conn": "127.0.0.1:58244 -> 127.0.0.1:27017"}
2022-10-20T16:42:56.381+0200	DEBUG	// 127.0.0.1:58244 -> 127.0.0.1:27017 	clientconn/conn.go:202	Request header: length:   366, id:   51, response_to:    0, opcode: OP_QUERY
2022-10-20T16:42:56.382+0200	DEBUG	// 127.0.0.1:58244 -> 127.0.0.1:27017 	clientconn/conn.go:203	Request message:
{
  "Flags": 0,
  "FullCollectionName": "admin.$cmd",
  "NumberToReturn": -1,
  "NumberToSkip": 0,
  "Query": {
    "$k": [
      "ismaster",
      "helloOk",
      "client",
      "compression"
    ],
    "ismaster": true,
    "helloOk": true,
    "client": {
      "$k": [
        "driver",
        "os",
        "platform",
        "version",
        "application"
      ],
      "driver": {
        "$k": [
          "name",
          "version"
        ],
        "name": "nodejs|mongosh",
        "version": "4.10.0"
      },
      "os": {
        "$k": [
          "type",
          "name",
          "architecture",
          "version"
        ],
        "type": "Darwin",
        "name": "darwin",
        "architecture": "arm64",
        "version": "21.6.0"
      },
      "platform": "Node.js v16.18.0, LE (unified)",
      "version": "4.10.0|1.6.0",
      "application": {
        "$k": [
          "name"
        ],
        "name": "mongosh 1.6.0"
      }
    },
    "compression": [
      "none"
    ]
  }
}



2022-10-20T16:42:56.383+0200	DEBUG	// 127.0.0.1:58244 -> 127.0.0.1:27017 	clientconn/conn.go:465	Response header: length:   205, id:    1, response_to:   51, opcode: OP_REPLY
2022-10-20T16:42:56.383+0200	DEBUG	// 127.0.0.1:58244 -> 127.0.0.1:27017 	clientconn/conn.go:466	Response message:
{
  "CursorID": 0,
  "Documents": [
    {
      "$k": [
        "ismaster",
        "maxBsonObjectSize",
        "maxMessageSizeBytes",
        "maxWriteBatchSize",
        "localTime",
        "minWireVersion",
        "maxWireVersion",
        "readOnly",
        "ok"
      ],
      "ismaster": true,
      "maxBsonObjectSize": 16777216,
      "maxMessageSizeBytes": 48000000,
      "maxWriteBatchSize": 100000,
      "localTime": {
        "$d": 1666276976382
      },
      "minWireVersion": 17,
      "maxWireVersion": 17,
      "readOnly": false,
      "ok": {
        "$f": 1
      }
    }
  ],
  "NumberReturned": 1,
  "ResponseFlags": 0,
  "StartingFrom": 0
}



2022-10-20T16:42:56.388+0200	DEBUG	// 127.0.0.1:58244 -> 127.0.0.1:27017 	clientconn/conn.go:465	Proxy response header: length:   329, id: 1382, response_to:   51, opcode: OP_REPLY
2022-10-20T16:42:56.389+0200	DEBUG	// 127.0.0.1:58244 -> 127.0.0.1:27017 	clientconn/conn.go:466	Proxy response message:
{
  "CursorID": 0,
  "Documents": [
    {
      "$k": [
        "helloOk",
        "ismaster",
        "topologyVersion",
        "maxBsonObjectSize",
        "maxMessageSizeBytes",
        "maxWriteBatchSize",
        "localTime",
        "logicalSessionTimeoutMinutes",
        "connectionId",
        "minWireVersion",
        "maxWireVersion",
        "readOnly",
        "ok"
      ],
      "helloOk": true,
      "ismaster": true,
      "topologyVersion": {
        "$k": [
          "processId",
          "counter"
        ],
        "processId": {
          "$o": "63513573e039770f84bcdb79"
        },
        "counter": {
          "$l": "0"
        }
      },
      "maxBsonObjectSize": 16777216,
      "maxMessageSizeBytes": 48000000,
      "maxWriteBatchSize": 100000,
      "localTime": {
        "$d": 1666276976387
      },
      "logicalSessionTimeoutMinutes": 30,
      "connectionId": 37,
      "minWireVersion": 0,
      "maxWireVersion": 17,
      "readOnly": false,
      "ok": {
        "$f": 1
      }
    }
  ],
  "NumberReturned": 1,
  "ResponseFlags": 8,
  "StartingFrom": 0
}



2022-10-20T16:42:56.391+0200	DEBUG	// 127.0.0.1:58244 -> 127.0.0.1:27017 	clientconn/conn.go:261	Header diff:
--- res header
+++ proxy header
@@ -1 +1 @@
-length:   205, id:    1, response_to:   51, opcode: OP_REPLY
+length:   329, id: 1382, response_to:   51, opcode: OP_REPLY

Body diff:
--- res body
+++ proxy body
@@ -5,3 +5,5 @@
       "$k": [
+        "helloOk",
         "ismaster",
+        "topologyVersion",
         "maxBsonObjectSize",
@@ -10,2 +12,4 @@
         "localTime",
+        "logicalSessionTimeoutMinutes",
+        "connectionId",
         "minWireVersion",
@@ -15,3 +19,16 @@
       ],
+      "helloOk": true,
       "ismaster": true,
+      "topologyVersion": {
+        "$k": [
+          "processId",
+          "counter"
+        ],
+        "processId": {
+          "$o": "63513573e039770f84bcdb79"
+        },
+        "counter": {
+          "$l": "0"
+        }
+      },
       "maxBsonObjectSize": 16777216,
@@ -20,5 +37,7 @@
       "localTime": {
-        "$d": 1666276976382
+        "$d": 1666276976387
       },
-      "minWireVersion": 17,
+      "logicalSessionTimeoutMinutes": 30,
+      "connectionId": 37,
+      "minWireVersion": 0,
       "maxWireVersion": 17,
@@ -31,3 +50,3 @@
   "NumberReturned": 1,
-  "ResponseFlags": 0,
+  "ResponseFlags": 8,
   "StartingFrom": 0



2022-10-20T16:42:59.040+0200	INFO	listener	clientconn/listener.go:196	Connection started	{"conn": "127.0.0.1:58246 -> 127.0.0.1:27017"}
2022-10-20T16:42:59.042+0200	DEBUG	// 127.0.0.1:58246 -> 127.0.0.1:27017 	clientconn/conn.go:202	Request header: length:   366, id:   52, response_to:    0, opcode: OP_QUERY
2022-10-20T16:42:59.043+0200	DEBUG	// 127.0.0.1:58246 -> 127.0.0.1:27017 	clientconn/conn.go:203	Request message:
{
  "Flags": 0,
  "FullCollectionName": "admin.$cmd",
  "NumberToReturn": -1,
  "NumberToSkip": 0,
  "Query": {
    "$k": [
      "ismaster",
      "helloOk",
      "client",
      "compression"
    ],
    "ismaster": true,
    "helloOk": true,
    "client": {
      "$k": [
        "driver",
        "os",
        "platform",
        "version",
        "application"
      ],
      "driver": {
        "$k": [
          "name",
          "version"
        ],
        "name": "nodejs|mongosh",
        "version": "4.10.0"
      },
      "os": {
        "$k": [
          "type",
          "name",
          "architecture",
          "version"
        ],
        "type": "Darwin",
        "name": "darwin",
        "architecture": "arm64",
        "version": "21.6.0"
      },
      "platform": "Node.js v16.18.0, LE (unified)",
      "version": "4.10.0|1.6.0",
      "application": {
        "$k": [
          "name"
        ],
        "name": "mongosh 1.6.0"
      }
    },
    "compression": [
      "none"
    ]
  }
}



2022-10-20T16:42:59.043+0200	DEBUG	// 127.0.0.1:58246 -> 127.0.0. [...]

2022-10-20 15:05 UTC, noisersup reviewed
Pg tests are failing after a couple of execution. Also 1 question

2022-10-21 09:37 UTC, w84thesun commented on internal/handlers/pg/msg_explain.go
> +			"explainVersion", "1",
Yeah, that's what MongoDB expects. It was passed as `int32` but when I added the test I figured out that it should be of type `string`.

2022-10-21 09:40 UTC, w84thesun commented on integration/commands_diagnostic_test.go
> +		queryPlanner map[string]any
Yes, removed it.

2022-10-21 09:40 UTC, w84thesun commented on integration/commands_diagnostic_test.go
> +			assert.NotEmpty(t, explainResult["queryPlanner"])
Added the check for type.

2022-10-21 12:41 UTC, w84thesun commented
@rumyantseva DeepCopy of the command document resolved the panics. At least I can't reproduce it anymore. It would be great if you can try it once more.

2022-10-21 13:55 UTC, w84thesun commented on internal/clientconn/conn.go
> +		filename := fmt.Sprintf("%s-%s.bin", time.Now().Format("2006-01-02-15-04-05"), c.netConn.RemoteAddr().String())
Changed to dashes as on Windows `:` is prohibited in file name 🤷

2022-10-21 14:42 UTC, rumyantseva approved these changes
I tired it! No panic anymore, and `queryPlanner` looks like an object indeed :)

2022-10-21 14:47 UTC, AlekSi approved these changes

2022-10-21 14:59 UTC, merged