Add text for empty pages
FerretDB/FerretDB pull request #1338
Opened 2022-10-27 11:50 UTC by Fashander

# Description

Closes #1324 .

## Readiness checklist

* [ ] I added tests for new functionality or bugfixes.
* [ ] I ran `task all`, and it passed.
* [ ] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [x] I ensured that the title is good enough for the changelog.
* [ ] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

2022-10-27 13:15 UTC, w84thesun submitted a review, later dismissed

2022-10-27 14:17 UTC, AlekSi requested changes
Docs building fails due to missing newlines at end of files

2022-10-31 07:55 UTC, AlekSi requested changes
Please revert changes in CHANGELOG.md

2022-11-01 16:14 UTC, AlekSi approved these changes

2022-11-01 17:45 UTC, merged