Configure blog in Docusaurus
FerretDB/FerretDB pull request #1756
Opened 2023-01-05 11:46 UTC by Fashander

# Description
Closes #{issue_number}.

## Readiness checklist

* [ ] I added unit tests for new functionality or bug fixes.
* [ ] I added integration tests for new functionality or bug fixes.
* [ ] I added compatibility tests for new functionality or bug fixes.
* [ ] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [ ] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [x] I ensured that the title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

2023-01-05 12:02 UTC, rumyantseva commented
@Fashander if you don't mind, I'll push github actions related code to this PR too (that's for my tomorrow's todo list as it's not a blocker at the moment).

2023-01-05 12:02 UTC, Fashander commented
@rumyantseva Sure, no problem.

2023-01-11 12:47 UTC, b1ron requested changes
Looks good and it's running locally. Link to https://tigrisdata.io/ is dead, I suggested a fix.

2023-01-11 12:47 UTC, b1ron commented on website/blog/2022-06-27-developers-need-ferretdb-stackoverflow-developer-survey-2022.md
> +Working with partners, like [Tigris Data](https://tigrisdata.io), we can even provide an alternative to MongoDB Atlas itself.
```suggestion
Working with partners, like [Tigris Data](https://www.tigrisdata.com/), we can even provide an alternative to MongoDB Atlas itself.
```

2023-01-11 13:05 UTC, rumyantseva commented on website/blog/2022-06-27-developers-need-ferretdb-stackoverflow-developer-survey-2022.md
> +Working with partners, like [Tigris Data](https://tigrisdata.io), we can even provide an alternative to MongoDB Atlas itself.
Nice catch!

2023-01-11 13:07 UTC, b1ron approved these changes

2023-01-11 13:07 UTC, w84thesun approved these changes

2023-01-11 13:10 UTC, noisersup submitted a review, later dismissed
:rocket:

2023-01-11 21:41 UTC, rumyantseva reviewed
Almost ready! We need to move the recent blog post, and then we should be ready to publish the new blog!

2023-01-12 02:34 UTC, chilagrow commented
> Almost ready! We need to move the recent blog post, and then we should be ready to publish the new blog!

`FerretDB v0.8.0 Beta` blog is missing.

2023-01-12 18:51 UTC, rumyantseva submitted a review, later dismissed
LGTM for now.

We will continue in the next PRs and issues.

2023-01-12 20:42 UTC, w84thesun submitted a review, later dismissed

2023-01-13 01:30 UTC, chilagrow submitted a review, later dismissed

2023-01-13 08:55 UTC, AlekSi approved these changes

2023-01-13 08:58 UTC, rumyantseva approved these changes
LGTM

2023-01-13 09:05 UTC, merged