Fix internal links and images
FerretDB/FerretDB pull request #1796
Opened 2023-01-13 15:51 UTC by Fashander

# Description

## Readiness checklist

* [ ] I added unit tests for new functionality or bug fixes.
* [ ] I added integration tests for new functionality or bug fixes.
* [ ] I added compatibility tests for new functionality or bug fixes.
* [ ] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [ ] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [x] I ensured that the title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

2023-01-13 16:53 UTC, AlekSi requested changes
This PR adds `.webp` files as blobs in git instead of using Git LFS. Please remove them, apply 9ba1f52f23a90f21d11ec1d4d4671f7640cf4b39, and re-add them

2023-01-13 17:26 UTC, AlekSi requested changes
Still the same problem. https://patch-diff.githubusercontent.com/raw/FerretDB/FerretDB/pull/1796.patch, search for "GIT binary patch".

And please remove .DS_Store

2023-01-13 17:30 UTC, Fashander commented
@AlekSi Okay. I'm on it,

2023-01-13 18:13 UTC, AlekSi commented
@Fashander There are conflicts now

2023-01-16 11:35 UTC, AlekSi approved these changes

2023-01-16 11:35 UTC, AlekSi commented on website/blog/2022-12-23-ferretdb-new-release-with-tls.md
> +image: ../static//img/blog/TLS.png
```suggestion
image: ../static/img/blog/TLS.png
```

2023-01-16 11:35 UTC, AlekSi commented on website/blog/2022-12-23-ferretdb-new-release-with-tls.md
> +![FerretDB 0.7.1 release](../static//img/blog/TLS.png)
```suggestion
![FerretDB 0.7.1 release](../static/img/blog/TLS.png)
```

2023-01-16 11:39 UTC, AlekSi requested changes
<img width="766" alt="CleanShot 2023-01-16 at 15 38 17@2x" src="https://user-images.githubusercontent.com/11512/212669663-3e35d7dd-7a27-4b46-8c42-89beb45761fe.png">

Please don't store .webp files with .png extension

2023-01-16 15:56 UTC, Fashander commented
@AlekSi Please, I need your help with this. Seems the `.webp` images are still not showing up despite adding it to `git lfs`.

2023-01-16 16:15 UTC, Fashander commented
> > Seems the .webp images are still not showing up despite adding it to git lfs.
> 
> It might be GitHub's problem: [github/docs#21798](https://github.com/github/docs/issues/21798)

Oh, that explains it. Thanks. What should I do to get this close to being done though? Should we wait for GitHub to resolve the issue?

2023-01-16 16:16 UTC, AlekSi commented
Nothing. The fact that they don't show up in PRs doesn't me they don't work: https://media.githubusercontent.com/media/FerretDB/FerretDB/ee9f09b57be451611efc407bb68665327d860978/website/static/img/blog/4ferrets.webp

2023-01-17 08:10 UTC, merged