Fix querying for an embedded field in array
FerretDB/FerretDB pull request #1886
Opened 2023-01-30 13:09 UTC by rumyantseva

# Description

Closes #1724.

## Readiness checklist

* [ ] I added/updated unit tests.
* [ ] I added/updated integration/compatibility tests.
* [ ] I added/updated comments and checked rendering.
* [ ] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [ ] I ensured that PR title is good enough for the changelog.
* [ ] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [ ] I marked all done items in this checklist.

2023-01-31 20:34 UTC, rumyantseva commented on integration/findandmodify_compat_test.go
> +					AssertEqualDocuments(t, compatMod, targetMod)
🙈

2023-02-01 02:57 UTC, chilagrow reviewed
I will take another look again, great work!

2023-02-01 02:57 UTC, chilagrow commented on internal/types/path.go
> +		var newNext []any
Just a suggestion, doesn't need to be applied but I feel this can be read easier if we have `current` and `next` :innocent:

2023-02-01 02:57 UTC, chilagrow commented on internal/types/document.go
> +// to get a value by path and modify it.
```suggestion
// to get a value by path and modify it.
// For example, if document is "foo": [{a: 1}, {a: 2}, {b: 3}], then d.GetAllByPath(Path({"foo", "a"})) will return ErrDocumentPathKeyNotFound.
```
Correct?

2023-02-01 02:57 UTC, chilagrow commented on internal/types/document.go
> +	return getAllByPath(d, path)
Should it be called `FilterByPath(...)`? The amazing doc string indicates it should only be called for querying and filtering but not for getting from the path :hugs:

2023-02-01 02:57 UTC, chilagrow commented on internal/types/path.go
> +				switch err {
I think switch is not necessary, a `if err != nil { break}` should be sufficient here. :hugs:

2023-02-01 02:57 UTC, chilagrow commented on internal/types/array.go
> +// GetAllByPath returns all values that match the path - a sequence of indexes and keys.
Doc string needs updating.

2023-02-01 02:57 UTC, chilagrow commented on internal/handlers/common/filter.go
> +				switch err {
Hmm, switch with `case nil:` and `default:` seems like it can be `if err != nil` :innocent:

2023-02-01 02:57 UTC, chilagrow commented on internal/handlers/common/filter.go
> +					for i := 0; i < docValue.Len(); i++ {
If docValue length is zero what should happen?

2023-02-01 06:49 UTC, chilagrow reviewed
Thanks for the awesome work!

2023-02-01 06:49 UTC, chilagrow commented on integration/count_compat_test.go
> +			filter: bson.D{{"v.food.bar", "world"}},
Does this supposed to be `v.food.bar` or `v.foo.bar`? :hugs:

2023-02-01 06:49 UTC, chilagrow commented on integration/query_comparison_compat_test.go
> +			filter: bson.D{{"v.food.bar", bson.D{{"$eq", "world"}}}},
I don't see anything in shareddata which matches `v.food.bar` but it's not using `emptyResult` so what is supposed to match this one?

2023-02-01 11:07 UTC, noisersup requested changes
That's a lot of refactoring! Thanks for your research and findings about update cases.

Few comments from me and 1 question!

2023-02-01 13:26 UTC, w84thesun reviewed
Discussed implementation details on the call.
Looks like there could be 2 possible options:
* combine `getAllByPath` and `getExactByPath` adding a parameter for the kind of result we are looking for and returning a slice of values;
* refactor those functions and turn `getExactByPath` into something like `filterByPath` which would be used for queries and filtering. 

Also as I understand there is an undocumented feature of dot notation which we probably want to write down somewhere.
It is so that when you are filtering with dot notation, the path `v.foo.bar` is acting more like regex `v.*foo.*bar` resulting in matches with the path `v.0.foo.0.bar`.
Although when you are trying to update a document with the dot notation path `v.foo.bar` it should be matched exactly in order to perform the correct update operation.

2023-02-02 02:04 UTC, chilagrow commented on integration/query_comparison_compat_test.go
> +			filter: bson.D{{"v.food.bar", bson.D{{"$eq", "world"}}}},
Still it should return `emptyResult` if it's incorrect array field. Or I am being blind on what's being matched. After all, both target and compat is matching _something_. So this test proves that implementation matches compat. But I don't what data it matches.

2023-02-02 02:09 UTC, chilagrow commented on internal/handlers/common/filter.go
> +					for i := 0; i < docValue.Len(); i++ {
@noisersup which test covers this scenario :hugs:? If not, could you suggest please?

2023-02-02 02:22 UTC, chilagrow commented
> Discussed implementation details on the call. Looks like there could be 2 possible options:
> 
> * combine `getAllByPath` and `getExactByPath` adding a parameter for the kind of result we are looking for and returning a slice of values;
> * refactor those functions and turn `getExactByPath` into something like `filterByPath` which would be used for queries and filtering.
> 
> Also as I understand there is an undocumented feature of dot notation which we probably want to write down somewhere. It is so that when you are filtering with dot notation, the path `v.foo.bar` is acting more like regex `v.*foo.*bar` resulting in matches with the path `v.0.foo.0.bar`. Although when you are trying to update a document with the dot notation path `v.foo.bar` it should be matched exactly in order to perform the correct update operation.

@rumyantseva @w84thesunmMind blown with the dot notation :see_no_evil:. Particularly regrex part. I think having specific function for filtering is way to go here. Because getting path and getting filters are sufficiently different. But let's ask others what they think.

Yes, documentation would be great help here!

Finally, I have a question. If I have a query `v.food.bar` it seems it matches newly added document at `v.0.foo.0.bar` since the test returns nonEmptyResult. I suppose, regex is applied there.
What about if I query `v.fo.bar`, does it match `v.0.foo.0.bar`?

2023-02-02 06:14 UTC, rumyantseva commented
@noisersup @w84thesun @chilagrow thank you, everyone, for your comments! I think I now have some ideas about what I should refactor (both tests and code need some changes). I think I should also leave some comments in tests to explain how they work, or maybe at least I can include the exact `_id` to the filter, so it's easier to understand which documents are matched in which tests.

2023-02-06 15:39 UTC, rumyantseva commented
I close this one for now as it doesn't make much sense, but I'd like to reuse some intermediate commits. I'll open a new PR with more actual approach.

2023-02-06 15:39 UTC, closed without merging