2615 envtoo shell read
FerretDB/FerretDB pull request #2626
Opened 2023-05-13 08:09 UTC by wqhhust

# Description

Closes #{2615}.

## Readiness checklist

* [ ] I added/updated unit tests.
* [ ] I added/updated integration/compatibility tests.
* [ ] I added/updated comments and checked rendering.
* [ ] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [ ] I ensured that PR title is good enough for the changelog.
* [ ] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Labels, Project and project's Sprint fields.
* [ ] I marked all done items in this checklist.

2023-05-13 09:57 UTC, AlekSi reviewed
Let's rename `cat` to `read` everywhere

2023-05-13 09:57 UTC, AlekSi commented on cmd/envtool/envtool.go
> +	currentDir, err := os.Getwd()
There is no need to do that – `os.Open` opens files in the current directory by default

2023-05-13 09:57 UTC, AlekSi commented on cmd/envtool/envtool.go
> +		f, err := os.Open(path)
Let's just use `os.ReadFile` followed by `fmt.Print(string(b))`

2023-05-13 11:34 UTC, wqhhust commented
done

![image](https://github.com/FerretDB/FerretDB/assets/5955201/f24c7d8d-f463-46af-b70e-fffafb5f5789)

2023-05-15 06:43 UTC, AlekSi commented
Please run `task fmt-yaml`, the re-request review (see the last point [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review)).

2023-05-16 11:10 UTC, rumyantseva requested changes
With the current approach `task pacakges` doesn't work anymore. I tried it on Mac, and it failed. But when I run `task packages` from the `main` branch, it works. So, it needs to be fixed.

<img width="1830" alt="Screenshot 2023-05-16 at 13 10 01" src="https://github.com/FerretDB/FerretDB/assets/1684673/1d0e8cf4-fc01-43b1-a06f-2a7511938de7">

2023-05-16 12:52 UTC, wqhhust commented
Added back the sh.  thx for your review

2023-05-16 13:56 UTC, rumyantseva approved these changes
Thanks for contributing! The proposed approach looks good to me.

I renamed the PR title, so it matches the issue title - we describe the command we implement.

2023-05-16 14:13 UTC, w84thesun approved these changes
LGTM!

2023-05-16 15:03 UTC, AlekSi approved these changes

2023-05-16 16:37 UTC, merged