Merges fuzztool into envtool #2547
FerretDB/FerretDB pull request #2645
Opened 2023-05-16 16:03 UTC by Aditya1404Sal

# Description

Closes #2547 .

## Readiness checklist

* [ ] I added/updated unit tests.
* [ ] I added/updated integration/compatibility tests.
* [ ] I added/updated comments and checked rendering.
* [ ] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [ ] I ensured that PR title is good enough for the changelog.
* [ ] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Labels, Project and project's Sprint fields.
* [ ] I marked all done items in this checklist.

2023-05-16 16:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FerretDB/FerretDB?pullRequest=2645) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FerretDB/FerretDB?pullRequest=2645) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FerretDB/FerretDB?pullRequest=2645) it.</sub>

2023-05-22 10:53 UTC, rumyantseva requested changes
Hi @Aditya1404Sal, thank you very much for your contribution!

The main objective of the task is to incorporate a new subcommand called `fuzz corpus` to `envtool`. So it can be called as `envtool fuzz corpus`. 

In the current implementation, there is a conflict between the files `fuzzcorpus.go` and `envtool.go` due to the presence of variables with identical names. Instead of this conflict, we can modify the implementation to utilize the `cli` already defined in `envtool.go`. For instance, the existing `cli` includes subcommands like `shell mkdir` or `shell read`. We can extend it further to incorporate `fuzz corpus` in a similar fashion.

I appreciate that you've implemented this command in a separate file called `fuzzcorpus.go`, and we can continue to keep it there. However, we don't need a separate `cli` definition in that file.

2023-05-23 17:40 UTC, Aditya1404Sal commented
@rumyantseva 
I'm really really grateful for your clarification and explanation 
 i will try to resolve this issue as soon as possible. 
 however i have University exams in 4 days is it fine if it takes longer for me to resolve this bug ?

2023-05-23 17:44 UTC, rumyantseva commented
@Aditya1404Sal no worries, please take your time, we can wait! And good luck with the exams! 🤞

2023-06-05 11:43 UTC, AlekSi requested changes
Please run `task fuzz-corpus` locally. You will see that it does not compile

2023-06-11 20:29 UTC, Aditya1404Sal commented
@AlekSi , i managed to resolve the compilation errors for `bin/task fuzz-corpus` but , i am unable to get past this error 
`
failed 18 hours ago in 1m 46s
4s
2s
48s
49s
0s
Run bin/task init
task: [init-integration] go mod tidy
task: [gen-version] go generate -x ./build/version
task: [init-tools] go mod tidy
task: [init-tools-golangci] go mod tidy
go run ./generate.go
task: [init-integration] go mod verify
task: [init-tools-golangci] go mod verify
task: [init-tools] go mod verify
package.txt: 
branch.txt: main
fatal: No names found, cannot describe anything.
panic: Failed to run "git describe --dirty": exit status 128

goroutine 18 [running]:
main.runGit({0xc00003a7a8?, 0x0?, 0x0?})
	/home/runner/work/FerretDB/FerretDB/build/version/generate.go:37 +0x11b
main.main.func1()
	/home/runner/work/FerretDB/FerretDB/build/version/generate.go:59 +0x9b
created by main.main
	/home/runner/work/FerretDB/FerretDB/build/version/generate.go:56 +0x85
exit status 2
build/version/version.go:69: running "go": exit status 1
task: Failed to run task "gen-version": exit status 1
Error: Process completed with exit code 201.
`

it seems that the error originates from a failure in running the "git describe --dirty" command and the absence of a variate in package.txt.

However i haven't made any changes to the build files.

Please provide me assistance on resolving this error

2023-06-12 08:39 UTC, AlekSi requested changes

2023-06-12 08:39 UTC, AlekSi commented on .github/workflows/go.yml
> +        working-directory: source
Please keep a newline there

2023-06-12 08:39 UTC, AlekSi commented on cmd/envtool/envtool.go
> +	}`cmd:""`
Please format code with `bin/task fmt`

2023-06-12 08:39 UTC, AlekSi commented on cmd/envtool/envtool.go
> +	generatedCorpus, err := generatedCorpus()
That logic should be in a separate function similar to `shellRead`, `packageVersion`, etc, not just in the `main` function

2023-06-12 08:40 UTC, AlekSi commented
@Aditya1404Sal Please run commands from https://github.com/FerretDB/FerretDB/blob/main/CONTRIBUTING.md#making-a-working-copy, then run `git fetch --all --tags`

2023-06-19 07:11 UTC, AlekSi commented on .github/workflows/go.yml
> +        working-directory: source
Not before `working-directory`, but after it. Your editor may remove it automatically; please change its configuration to prevent that

2023-06-20 07:46 UTC, rumyantseva commented
@Aditya1404Sal please feel free to ping me if you have questions or need some help with the PR.

2023-06-20 18:30 UTC, Aditya1404Sal commented
@rumyantseva Thank you ! i really need some help 
i can't figure out how to resolve this set-up environment error
```
2023-06-15T08:44:30.316Z	INFO	envtool/envtool.go:662	Copying from  to .
2023-06-15T08:44:30.316Z	FATAL	envtool/envtool.go:455	[envtool.go:486 main.collectFiles.func1] lstat : no such file or directory
main.copyCorpus
	/home/runner/work/FerretDB/FerretDB/cmd/envtool/envtool.go:455
main.main
	/home/runner/work/FerretDB/FerretDB/cmd/envtool/envtool.go:663
runtime.main
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/proc.go:250
exit status 1
task: Failed to run task "env-setup": exit status 1
```
i've checked the collectFiles & copyCorpus functions but can't find any problems with them 
the problem might have something to do with the path variable , but this is speculative.
```
switch ctx.Command() {
	case "fuzz corpus <src> <dst>":
		switch cli.Fuzz.Corpus.Src {
		case "seed":
			src = seedCorpus
		case "generated":
			src = generatedCorpus
		default:
			src, err = filepath.Abs(cli.Fuzz.Corpus.Src)
			if err != nil {
				logger.Fatal(err)
			}
		}

		switch cli.Fuzz.Corpus.Dst {
		case "seed":
			// Because we would need to add `/testdata/fuzz` back, and that's not very easy.
			logger.Fatal("Copying to seed corpus is not supported.")
		case "generated":
			dst = generatedCorpus
		default:
			dst, err = filepath.Abs(cli.Fuzz.Corpus.Dst)
			if err != nil {
				logger.Fatal(err)
			}
		}
	case "setup":
		err = setup(ctx2, logger)
	case "shell mkdir <path>":
		err = shellMkDir(cli.Shell.Mkdir.Paths...)
	case "shell rmdir <path>":
		err = shellRmDir(cli.Shell.Rmdir.Paths...)
	case "shell read <path>":
		err = shellRead(os.Stdout, cli.Shell.Read.Paths...)
	case "package-version":
		err = packageVersion(os.Stdout, versionFile)
	case "tests shard":
		err = testsShard(os.Stdout, cli.Tests.Shard.Index, cli.Tests.Shard.Total)
	default:
		err = fmt.Errorf("unknown command: %s", ctx.Command())

		if err != nil {
			printDiagnosticData(err, logger)
			os.Exit(1)
		}
	}
```
I am very sorry for my incompetancy , but i'm really lost about what my next step should be 
please provide me with some assistance

2023-06-21 12:20 UTC, rumyantseva commented
@Aditya1404Sal then let's start by running a stable code. Could you please check out the latest `main` from the FerretDB repo, init the tooling and run tests through `task test-unit` (see https://github.com/FerretDB/FerretDB/blob/main/CONTRIBUTING.md for more details)? This way we can understand if your environment is ok. If something doesn't work please post the exact commands your run and the exact responses you get. Feel free to ping me on our community Slack for a faster response.

2023-07-18 07:46 UTC, AlekSi submitted a review, later dismissed

2023-07-18 08:06 UTC, chilagrow submitted a review, later dismissed
Just super minor comment

2023-07-18 10:38 UTC, AlekSi commented on cmd/envtool/envtool.go
> +		} `cmd:"" help:"Print sharded integration tests"`
wow, thanks

2023-07-18 10:45 UTC, AlekSi approved these changes

2023-07-18 19:00 UTC, noisersup approved these changes

2023-07-19 05:12 UTC, chilagrow approved these changes
:rocket:

2023-07-19 07:36 UTC, AlekSi approved these changes

2023-07-19 07:57 UTC, rumyantseva approved these changes
LGTM!

2023-07-19 07:57 UTC, merged