Add blog post for FerretDB v1.8.0
FerretDB/FerretDB pull request #3198
Opened 2023-08-14 11:06 UTC by Fashander

# Description

## Readiness checklist

- [ ] I added/updated unit tests (and they pass).
- [ ] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [ ] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

2023-08-14 11:15 UTC, ptrfarkas approved these changes

2023-08-14 12:19 UTC, AlekSi commented on website/blog/2023-08-14-ferretdb-new-release-v180.md
> +For the `$match` aggregation stage, you can use it like this: `{ $match: { $expr: { <aggregation expression> } } }`.
Or could just use `{ <aggregation expression> }`, without both `$match` and `$expr`

2023-08-14 12:43 UTC, AlekSi commented on website/blog/2023-08-14-ferretdb-new-release-v180.md
> +For the `$match` aggregation stage, you can use it like this: `db.col.aggregate({<aggregation expression>})`.
There is no `$match` stage in the example that supposedly demonstrates the usage of it.

Please do your own proofreading and review first.

2023-08-14 14:56 UTC, AlekSi requested changes

2023-08-14 14:56 UTC, AlekSi commented on website/blog/2023-08-14-ferretdb-new-release-v180.md
> +  FerretDB v1.8.0 has just been released with new features, bug fixes, and improvements to the SQLite and PostgreSQL backend.
```suggestion
  FerretDB v1.8.0 has just been released with new features, bug fixes, and improvements to the SQLite and PostgreSQL backends.
```

2023-08-14 14:56 UTC, AlekSi commented on website/blog/2023-08-14-ferretdb-new-release-v180.md
> +We've also added support for the `$expr` operator in evaluation queries when using the `find` command, and in aggregation operations within the `$match` aggregation stage.
Could you please explain to me what is "evaluation queries"? and how `$match` aggregation stage uses aggregation operations?

2023-08-14 14:56 UTC, AlekSi commented on website/blog/2023-08-14-ferretdb-new-release-v180.md
> +And for the `$match` aggregation stage, you can use the operator like this: `db.col.aggregate({ $match: { $expr: <expression> } })`.
Why would someone do something like that?

2023-08-15 10:16 UTC, AlekSi approved these changes

2023-08-15 10:17 UTC, merged