Add blog post
FerretDB/FerretDB pull request #4639
Opened 2024-11-26 18:56 UTC by Fashander

# Description

Closes FerretDB/engineering#229.

## Readiness checklist

- [ ] I added/updated unit tests (and they pass).
- [ ] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [ ] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

2024-11-27 00:44 UTC, chilagrow approved these changes

2024-11-27 06:26 UTC, AlekSi commented
> [x] I ensured that PR title is good enough for the changelog.

@Fashander srsly?

2024-11-27 06:27 UTC, AlekSi requested changes

2024-11-27 06:27 UTC, AlekSi commented on .DS_Store
Please remove it from commit and it to your global .gitignore

2024-11-27 17:18 UTC, AlekSi requested changes

2024-11-27 17:18 UTC, AlekSi commented on .gitignore
> +.DS_Store
Please check the first two lines of this file

2024-11-28 00:55 UTC, chilagrow approved these changes

2024-11-29 05:18 UTC, chilagrow approved these changes

2024-11-29 15:05 UTC, AlekSi approved these changes

2024-11-29 15:12 UTC, merged