Make linter to enforce our preferred types order in type switch #527
FerretDB/FerretDB pull request #654
Opened 2022-05-30 07:36 UTC by fenogentov

2022-05-30 15:48 UTC, AlekSi requested changes
Let's move the tool into tools/check-switch.go, hook it into tools/tools.go, tools/go.mod

2022-05-30 18:11 UTC, AlekSi commented on go.mod
> +require golang.org/x/mod v0.6.0-dev.0.20220106191415-9b9b3d81d5e3 // indirect
Both those changes should not be there

2022-05-31 10:18 UTC, seeforschauer commented
@fenogentov would you please fix linters?

2022-05-31 10:23 UTC, fenogentov commented
> @fenogentov would you please fix linters?

this is an example of how the new linter works

2022-06-02 06:06 UTC, AlekSi commented on tools/tools.go
> +//go:generate go install check-switch.go
Let build it into `../bin/` like we do with other tools

2022-06-02 06:06 UTC, AlekSi commented on Taskfile.yml
> +#      - go vet -vettool=$(which check-switch) ./...
I think `../bin/check-switch` should work

2022-06-08 11:48 UTC, AlekSi commented on tools/check-switch/check-switch_test.go
> +	analysistest.Run(t, testdata, Analyzer, "a")
Shouldn't we check results?

2022-06-08 11:48 UTC, AlekSi commented on Taskfile.yml
> +#      - go vet -vettool=$(which ./bin/check-switch) ./...
We should run the linter

2022-06-08 11:48 UTC, AlekSi commented on tools/check-switch/testdata/src/a/a.go
> +package a
Can it be just in `testdata/a.go`

2022-06-08 13:13 UTC, AlekSi commented on Taskfile.yml
> +#      - go vet -vettool=$(which ./bin/check-switch) ./...
Let's start with better error messages :) Then please send PRs that fix those problems

2022-06-20 18:49 UTC, AlekSi requested changes

2022-06-20 18:49 UTC, AlekSi commented on Taskfile.yml
> +      - go vet -vettool=$(which ./bin/check-switch) ./...
```suggestion
      - go vet -vettool=./bin/check-switch ./...
```

There should not be a need to use `which` if we provide a path

2022-06-20 18:49 UTC, AlekSi commented on tools/tools.go
> +//go:generate go build -v -o ../bin/ check-switch/check-switch.go
```suggestion
//go:generate go build -v -o ../bin/ ./check-switch
```

To use package path as in other lines

2022-06-20 18:49 UTC, AlekSi commented on tools/check-switch/testdata/src/a/a.go
> +	case int32:
```suggestion
	case int32, int64:
```

How that case will be handled? Let's test it

2022-06-20 18:49 UTC, AlekSi commented on tools/check-switch/check-switch.go
> +								pass.Reportf(n.Pos(), "non-observance of the preferred order of types")
Can we add types to the error message?

2022-06-20 18:49 UTC, AlekSi commented on tools/check-switch/check-switch.go
> +func run(pass *analysis.Pass) (interface{}, error) {
That function would benefit from comment explaining how it works.
And let's add some comments inside

2022-06-20 18:49 UTC, AlekSi commented on tools/check-switch/check-switch.go
> +	"time.Time": 7,
Why only `time.Time` has a package qualifier? Why not, for example, `types.Timestamp` below?

2022-06-20 18:49 UTC, AlekSi commented on internal/handlers/common/filter.go
> +	case typeCodeObject:
Object/document should go before array. I guess that change is unrelated and not caught by the linter?

2022-06-29 17:10 UTC, AlekSi reviewed
@fenogentov How do you run this test? It does not work for me:

```
~/C/F/F/t/checkswitch (pr/fenogentov/654) -> go test

src/a/a.go:7:2: cannot find package "github.com/FerretDB/FerretDB/internal/types" in any of:
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/github.com/FerretDB/FerretDB/internal/types (from $GOROOT)
        /Users/aleksi/Code/FerretDB/FerretDB/tools/checkswitch/testdata/src/github.com/FerretDB/FerretDB/internal/types (from $GOPATH)
/Users/aleksi/Code/FerretDB/FerretDB/tools/checkswitch/testdata/src/a/a.go:7:2: could not import github.com/FerretDB/FerretDB/internal/types (invalid package name: "")
/Users/aleksi/Code/FerretDB/FerretDB/tools/checkswitch/testdata/src/a/a.go:45:7:        previous case
/Users/aleksi/Code/FerretDB/FerretDB/tools/checkswitch/testdata/src/a/a.go:74:7:        previous case
/Users/aleksi/Code/FerretDB/FerretDB/tools/checkswitch/testdata/src/a/a.go:105:7:       previous case
/Users/aleksi/Code/FerretDB/FerretDB/tools/checkswitch/testdata/src/a/a.go:136:7:       previous case
--- FAIL: TestCheckSwitch (0.19s)
    analysistest.go:296: error analyzing checkswitch@a: analysis skipped due to errors in package
FAIL
exit status 1
FAIL    github.com/FerretDB/FerretDB/tools/checkswitch  0.327s
```

2022-07-06 06:45 UTC, AlekSi commented on tools/checkswitch/checkswitch.go
> -	"CString": 15,
@fenogentov ^ I think we should keep type codes in that map and group items

2022-07-06 06:45 UTC, AlekSi reviewed
https://github.com/FerretDB/FerretDB/pull/654#discussion_r914470334

2022-07-07 06:11 UTC, AlekSi commented on tools/checkswitch/checkswitch.go
> -	"CString": 15,
> group items

That was done

> keep type codes

That wasn't :) See affe64fefe55d8842c5b0d8f085ecdfb9e508fbb

2022-07-07 06:12 UTC, AlekSi reviewed
https://github.com/FerretDB/FerretDB/pull/654#discussion_r915493790

2022-07-12 14:05 UTC, AlekSi reviewed
Please resolve merge conflicts

2022-07-27 06:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FerretDB/FerretDB?pullRequest=654) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/FerretDB/FerretDB?pullRequest=654) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: AlekSi<br/>:white_check_mark: fenogentov<br/>:x: Katerina Bletsch<br/><hr/>**Katerina Bletsch** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FerretDB/FerretDB?pullRequest=654) it.</sub>

2022-08-02 13:32 UTC, AlekSi approved these changes

2022-08-02 13:33 UTC, AlekSi approved these changes

2022-08-02 13:38 UTC, merged