Support $rename field update operator
FerretDB/FerretDB pull request #670
Opened 2022-05-31 16:28 UTC by fenogentov

Closes #626

2022-06-01 10:15 UTC, AlekSi commented on integration/update_test.go
> +			require.NoError(t, err)
I think that it becomes a problem that, unlike `find` tests, each `update` test uses its own data set. Let's put that PR on pause until we decide if we want to do something about that. Created #674 for tracking

2022-10-02 08:33 UTC, AlekSi requested changes
Please also resolve merge conflicts

2022-10-02 08:33 UTC, AlekSi commented on integration/update_test.go
> +			require.NoError(t, err)
Let's hook into update_field_compat_test.go instead of using test-specific data set

2022-10-03 11:24 UTC, w84thesun requested changes

2022-10-03 11:24 UTC, w84thesun commented on internal/handlers/common/update.go
> +		case "$rename":
Please move that code to the new function `processRenameFieldExpression`.

2022-10-05 09:31 UTC, rumyantseva reviewed
Let's make the necessary changes.

2023-01-13 19:49 UTC, rumyantseva commented
Supported in #1753.

2023-01-13 19:49 UTC, closed without merging