Build .rpm and .deb packages
FerretDB/FerretDB pull request #739
Opened 2022-06-15 16:17 UTC by fenogentov

Closes #734.

2022-06-16 06:38 UTC, AlekSi requested changes

2022-06-16 06:38 UTC, AlekSi commented on Taskfile.yml
> +      - mkdir -p ./build/rpm
That could be done using `dir:`: https://taskfile.dev/usage/#task-directory

2022-06-16 06:38 UTC, AlekSi commented on Taskfile.yml
> +      - nfpm pkg -f .nfpm.yaml -t ./build/deb/ferretdb_{{.VERSION}}.deb
Let's install `nfpm` in tools.go

2022-06-29 17:25 UTC, AlekSi commented on Taskfile.yml
> +        sh: cat ../../internal/util/version/version.txt | grep -oP '^(.+?)(?=-)'
```
task: Failed to run task "packager": task: Command "cat ../../internal/util/version/version.txt | grep -oP '^(.+?)(?=-)'" failed: exit status 2
```

Let's wait until #798 is merged, then change generate.go to generate another file with a clean version

2022-07-06 13:35 UTC, AlekSi reviewed
https://github.com/FerretDB/FerretDB/pull/739#discussion_r914846510

2022-07-07 04:23 UTC, fenogentov commented
> [#739 (comment)](https://github.com/FerretDB/FerretDB/pull/739#discussion_r914846510)

#739 is `Merged`
it got me confused

2022-07-09 13:09 UTC, AlekSi commented
Actually, why we need `grep` at all? Version generated by `git describe --tags --dirty` should be good enough

2022-07-11 08:19 UTC, fenogentov commented
> Actually, why we need `grep` at all? Version generated by `git describe --tags --dirty` should be good enough

We are satisfied with the file "ferretdb_v0.4.0-56-g15af921-dirty.deb"?
Or is it "ferretdb_v0.4.0-56-g15af921.deb"?

2022-07-12 14:05 UTC, AlekSi reviewed
Let's also tweak CI config to build package there, just for testing for now, without actually uploading them anywhere

2022-07-12 14:05 UTC, AlekSi commented on Taskfile.yml
> +        sh: git describe --tags --dirty
```suggestion
      VERSION:
        sh: cat internal/util/version/gen/version.txt
```

2022-07-12 14:05 UTC, AlekSi commented on Taskfile.yml
> +        sh: git describe --tags --dirty
The same what we use above

2022-07-12 14:05 UTC, AlekSi commented on Taskfile.yml
> +      - go build -v -o ./bin/ ./cmd/ferretdb
We should use existing `build-testcover`

2022-07-17 05:41 UTC, AlekSi approved these changes

2022-07-17 05:43 UTC, merged

2022-07-17 05:48 UTC, AlekSi commented
Thank you!