Implement `getFreeMonitoringStatus` stub
FerretDB/FerretDB pull request #751
Opened 2022-06-20 17:36 UTC by noisersup

Closes #745.

# Checklist

* [x] Tests are added for new functionality or fixed bugs.
* [x] `task all` passes.

See CONTRIBUTING.md for more details.

2022-06-21 14:15 UTC, noisersup commented
> I'm not sure why `task lint` return an error on my machine.
> 
> ```
> internal/handlers/common/msg_hostinfo.go:65:42: directive `//nolint:staticcheck // good enough for GOOS` is unused for linter "staticcheck"
> (nolintlint)
>                                 "type", strings.Title(runtime.GOOS), //nolint:staticcheck // good enough for GOOS
>                                                                      ^
> task: Failed to run task "lint-golangci-lint": exit status 1
> ```
> 
> I didn't even change `internal/handlers/common/msg_hostinfo.go` file.

Fixed with `bin/golangci-lint cache clean`

2022-06-21 14:29 UTC, AlekSi commented
#756

2022-06-21 15:02 UTC, AlekSi requested changes

2022-06-21 15:05 UTC, noisersup commented on internal/handlers/common/msg_getfreemonitoringstatus.go
> +			"message", "monitoring is not enabled", // Should I include that?
whoops, sorry for overlooking

2022-06-21 18:36 UTC, AlekSi submitted a review, later dismissed

2022-06-21 18:36 UTC, AlekSi commented on internal/handlers/common/msg_listcommands.go
> +		Help:    "MsgGetFreeMonitoringStatus returns the status of free Cloud monitoring",
```suggestion
		Help:    "MsgGetFreeMonitoringStatus returns the status of free Cloud monitoring.",
```

2022-06-22 05:46 UTC, AlekSi approved these changes

2022-06-22 07:23 UTC, rumyantseva approved these changes
LGTM

2022-06-22 08:19 UTC, seeforschauer commented on integration/commands_freemonitoring_test.go
> +		}
I would suggest here reducing complexity.
```go
                        AssertEqualDocuments(t, it, z)
                        continue
		} 
		assert.Equal(t, m[k], item)
```

2022-06-22 08:20 UTC, seeforschauer commented on internal/handlers/common/msg_listcommands.go
> +		Help:    "MsgGetFreeMonitoringStatus returns the status of free Cloud monitoring.",
Doesn't it has to be in a small letter? 
```suggestion
		Help:    "MsgGetFreeMonitoringStatus returns the status of free cloud monitoring.",
```

2022-06-22 08:21 UTC, seeforschauer commented on internal/handlers/handlers.go
> +	// MsgGetFreeMonitoringStatus returns the status of free Cloud monitoring.
same here

2022-06-22 11:49 UTC, seeforschauer approved these changes

2022-06-22 12:11 UTC, noisersup commented
> wait, tests not passing :)

That's weird, I'm sure that I have run `test all` before pushing.

2022-06-22 12:13 UTC, noisersup commented
there are some [authentication problems](https://github.com/FerretDB/FerretDB/runs/7003515496?check_suite_focus=true#step:7:17) in tests I guess

2022-06-22 13:07 UTC, AlekSi commented
That was a temporary GitHub hiccup

2022-06-22 14:03 UTC, seeforschauer approved these changes

2022-06-22 14:05 UTC, AlekSi approved these changes

2022-06-22 14:05 UTC, merged