Improve path api
FerretDB/FerretDB pull request #973
Opened 2022-08-01 17:46 UTC by w84thesun

# Description

This PR refs #803.

In that PR I added the set of `Document` methods working with `Path`. They would be needed later to implement dot notation support for update operators.

Here we came up with the decision that a `Path` with one element is the correct path and it's a caller's responsibility to check where that case is applicable.

## Readiness checklist

* [ ] I added tests for new functionality or bugfixes.
* [ ] I ran `task all`, and it passed.
* [ ] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [ ] (for maintainers only) I set Reviewers, Assignee, Labels, Project and project's Sprint fields.
* [ ] I marked all done items in this checklist.

2022-08-01 18:16 UTC, rumyantseva approved these changes
the `SetByPath` method is complicated but it looks correct from first sight.
I guess we will add integration tests as well as unit tests, so we will have some more cases / some real cases covered.

2022-08-01 18:47 UTC, AlekSi requested changes

2022-08-01 18:47 UTC, AlekSi commented on internal/types/document.go
> +// If the Path has only one element, it sets the value for the given key.
That does not sound right

2022-08-01 18:47 UTC, AlekSi commented on internal/types/document.go
> +// If the Path has only one element, it sets the value for the given key.
Looks like incorrect copy&paste

2022-08-01 19:00 UTC, w84thesun commented on internal/types/document.go
> +// If the Path has only one element, it sets the value for the given key.
Yeah... Updated.

2022-08-01 19:00 UTC, w84thesun commented on internal/types/document.go
> +// If the Path has only one element, it sets the value for the given key.
Updated

2022-08-01 19:17 UTC, AlekSi approved these changes

2022-08-02 07:04 UTC, rumyantseva approved these changes
LGTM

2022-08-02 07:04 UTC, merged